services:
  ################## MYSQL ###########################
  #username password :: root/root
  mysql:
    profiles:
      - mysql
    image: mysql:8.0.40
    container_name: mysql-db-8.0.40
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin -h 'localhost' -u root -proot ping --silent" ]
      interval: 30s
      timeout: 30s
      retries: 3
  ################## MYSQL ######################

  ################## POSTGRES ###########################
  postgres:
    profiles:
      - postgres
    image: postgres:16
    container_name: postgres-16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      #- ./docker/postgres/db:/var/lib/postgresql/data
      - ./docker/postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
  ################## POSTGRES ###########################