services:
  ################## MYSQL ###########################
  #username password :: root/root
  mysql:
    image: mysql:8.0.40
    container_name: mysql-db-8.0.40
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin -h 'localhost' -u root -proot ping --silent" ]
      interval: 30s
      timeout: 30s
      retries: 3
  ################## MYSQL ######################