services:
  ################## MYSQL ###########################
  #username password :: root/root
  mysql:
    profiles:
      - mysql
    image: mysql:9.4.0
    container_name: mysql-db-9.4.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/mysqldata:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin -h 'localhost' -u root -proot ping --silent" ]
      interval: 30s
      timeout: 30s
      retries: 3
  ################## MYSQL ######################

  ################## POSTGRES ###########################
  postgres:
    profiles:
      - postgres
    image: postgres:17.6
    container_name: postgres-17.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/postgresdata:/var/lib/postgresql/data
      - ./docker/postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
  ################## POSTGRES ###########################